### ISSUE TITLE
Improve application startup and runtime management

### ISSUE THREAD

**Issue by fteychene** [dhall-mock/dhall-mock#74]
## Goal

We start two runtimes with tasks, handlers for system signals and channels to graceful stop.
Currently it sork but we have some trouble in the main to make it work and it's hard to start only interesting parts in integration testing

We should manage to change how we start runtimes and tasks in these runtimes

**Comment by fteychene** [comment]
Update to bug

Currently when stopping the server we have a panic
```
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.20/src/runtime/enter.rs:38:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by harksin** [comment]
do we close ?

**Comment by fteychene** [comment]
Yep let's close
Will recreate another issue if we need to improve these topics
